/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    ForecastDialog: typeof import('./../components/List/ForecastDialog.vue')['default']
    ForecastItem: typeof import('./../components/List/ForecastItem.vue')['default']
    Icon: typeof import('./../components/Base/Icon.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MobileTabs: typeof import('./../components/Layout/MobileTabs.vue')['default']
    NavBar: typeof import('./../components/Layout/NavBar.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreForecast: typeof import('./../components/Forecast/ScoreForecast.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TeamLogo: typeof import('./../components/Team/TeamLogo.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UserMenu: typeof import('./../components/Layout/UserMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
